name: task-2-docker-web-mosalam-com

include:
  - ./composefiles/shared.yaml
  - ./composefiles/proxy.yaml
  - ./composefiles/app.yaml
  - ./composefiles/database.yaml
  - ./composefiles/monitoring.yaml