CREATE TABLE IF NOT EXISTS todos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO todos (title)
SELECT 'Initial row from MySQL volume'
WHERE NOT EXISTS (SELECT 1 FROM todos WHERE title = 'Initial row from MySQL volume');

CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'exporterpass123' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
